- name: Install dependency packages
  apt:
    name:
      # - nginx
      # - supervisor
      - docker.io
    state: present

- name: Make sure docker is running
  systemd:
    state: started
    name: docker

- name: Make sure docker is enabled
  systemd:
    name: docker
    enabled: yes

- name: Install pip depedences
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - docker

- name: Pull docker images {{ image_name }}:{{ image_version | default('latest') }}
  docker_image:
    state: present
    name: "{{ image_name }}"
    tag: "{{ image_version | default('latest') }}"

- name: Container present
  docker_container:
    name: "{{ container_name }}"
    state: started
    image: "{{ image_name }}:{{ image_version | default('latest') }}"
    ports:
      - "{{ host_port | default('80') }}:{{ container_port | default('80') }}"
