- name: Install dependency packages
  apt:
    name:
      - nginx
      - supervisor
      - docker.io
    state: present

- name: Make sure docker is running
  systemd:
    state: started
    name: docker

- name: Make sure docker is enabled
  systemd:
    name: docker
    enabled: yes

- name: Install pip depedences
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - docker

# - name: Pull docker images ubuntu:18.04
#   docker_image:
#     state: present
#     name: ubuntu
#     tag: "18.04"
